### ISSUE TITLE
getPipeline does not appear to work at all

### ISSUE THREAD

**Issue by higstar** [Insightly/insightly-python#1]
Seems the call to generateRequest() is incorrect:
Traceback (most recent call last):
  File "C:\Users\axh\Documents\GitHub\Insightly_python\insightly.py", line 457, in test
    pipeline = self.getPipeline(pipelines[0]['PIPELINE_ID'])
  File "C:\Users\axh\Documents\GitHub\Insightly_python\insightly.py", line 1278, in getPipeline
    text = self.generateRequest('/v2.1/Pipelines/' + str(id))
TypeError: generateRequest() takes exactly 4 arguments (2 given)

**Comment by higstar** [comment]
The following are broken:
getEmailComments()
getEvent()
getPipeline()

These all put calls into gnerateRequest() with only the url argument set, no method or data.
Two fix options:
a) set defaults (i.e. generateRequest(self, url, method = 'GET', data = '')
b) fix the three calls

I chose a, because it has much less risk of unintended consequences.

Will add a pull request shortly.
